#spring.application.name=
#spring.main.web-application-type=reactive
#

server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
#              - G
#            allowed-methods:
