{
  "type": "record",
  "name": "TripDetails",
  "namespace": "org.example.sharedlibs.avro",
  "fields": [
    {
      "name": "tripId",
      "type": "string"
    },
    {
      "name": "userId",
      "type": "string"
    },
     {
      "name": "drive",
      "type": ["DriverDetails","null"]
    },
    {
      "name": "source",
      "type": "Location"
    },
    {
      "name": "destination",
      "type": "Location"
    },
    {
      "name": "tripStatus",
           "type": "TRIP_STATUS"

    }
  ]
}