/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.sharedlibs;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TripDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5622548467483267657L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TripDetails\",\"namespace\":\"org.example.sharedlibs\",\"fields\":[{\"name\":\"tripId\",\"type\":\"string\"},{\"name\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"addressLine1\",\"type\":\"string\"},{\"name\":\"addressLine2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"coordinate\",\"type\":{\"type\":\"record\",\"name\":\"Coordinate\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"provider\",\"type\":\"string\"},{\"name\":\"source\",\"type\":\"string\"}]}},{\"name\":\"destination\",\"type\":\"Location\"},{\"name\":\"tripStatus\",\"type\":{\"type\":\"enum\",\"name\":\"TRIP_STATUS\",\"symbols\":[\"STARTED\",\"IN_PROGRESS\",\"COMPLETED\",\"CANCELLED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TripDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TripDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TripDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TripDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TripDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TripDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TripDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TripDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TripDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence tripId;
  private org.example.sharedlibs.Location source;
  private org.example.sharedlibs.Location destination;
  private org.example.sharedlibs.TRIP_STATUS tripStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TripDetails() {}

  /**
   * All-args constructor.
   * @param tripId The new value for tripId
   * @param source The new value for source
   * @param destination The new value for destination
   * @param tripStatus The new value for tripStatus
   */
  public TripDetails(java.lang.CharSequence tripId, org.example.sharedlibs.Location source, org.example.sharedlibs.Location destination, org.example.sharedlibs.TRIP_STATUS tripStatus) {
    this.tripId = tripId;
    this.source = source;
    this.destination = destination;
    this.tripStatus = tripStatus;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tripId;
    case 1: return source;
    case 2: return destination;
    case 3: return tripStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tripId = (java.lang.CharSequence)value$; break;
    case 1: source = (org.example.sharedlibs.Location)value$; break;
    case 2: destination = (org.example.sharedlibs.Location)value$; break;
    case 3: tripStatus = (org.example.sharedlibs.TRIP_STATUS)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tripId' field.
   * @return The value of the 'tripId' field.
   */
  public java.lang.CharSequence getTripId() {
    return tripId;
  }


  /**
   * Sets the value of the 'tripId' field.
   * @param value the value to set.
   */
  public void setTripId(java.lang.CharSequence value) {
    this.tripId = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public org.example.sharedlibs.Location getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(org.example.sharedlibs.Location value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'destination' field.
   * @return The value of the 'destination' field.
   */
  public org.example.sharedlibs.Location getDestination() {
    return destination;
  }


  /**
   * Sets the value of the 'destination' field.
   * @param value the value to set.
   */
  public void setDestination(org.example.sharedlibs.Location value) {
    this.destination = value;
  }

  /**
   * Gets the value of the 'tripStatus' field.
   * @return The value of the 'tripStatus' field.
   */
  public org.example.sharedlibs.TRIP_STATUS getTripStatus() {
    return tripStatus;
  }


  /**
   * Sets the value of the 'tripStatus' field.
   * @param value the value to set.
   */
  public void setTripStatus(org.example.sharedlibs.TRIP_STATUS value) {
    this.tripStatus = value;
  }

  /**
   * Creates a new TripDetails RecordBuilder.
   * @return A new TripDetails RecordBuilder
   */
  public static org.example.sharedlibs.TripDetails.Builder newBuilder() {
    return new org.example.sharedlibs.TripDetails.Builder();
  }

  /**
   * Creates a new TripDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TripDetails RecordBuilder
   */
  public static org.example.sharedlibs.TripDetails.Builder newBuilder(org.example.sharedlibs.TripDetails.Builder other) {
    if (other == null) {
      return new org.example.sharedlibs.TripDetails.Builder();
    } else {
      return new org.example.sharedlibs.TripDetails.Builder(other);
    }
  }

  /**
   * Creates a new TripDetails RecordBuilder by copying an existing TripDetails instance.
   * @param other The existing instance to copy.
   * @return A new TripDetails RecordBuilder
   */
  public static org.example.sharedlibs.TripDetails.Builder newBuilder(org.example.sharedlibs.TripDetails other) {
    if (other == null) {
      return new org.example.sharedlibs.TripDetails.Builder();
    } else {
      return new org.example.sharedlibs.TripDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for TripDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TripDetails>
    implements org.apache.avro.data.RecordBuilder<TripDetails> {

    private java.lang.CharSequence tripId;
    private org.example.sharedlibs.Location source;
    private org.example.sharedlibs.Location.Builder sourceBuilder;
    private org.example.sharedlibs.Location destination;
    private org.example.sharedlibs.Location.Builder destinationBuilder;
    private org.example.sharedlibs.TRIP_STATUS tripStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.sharedlibs.TripDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.source)) {
        this.source = data().deepCopy(fields()[1].schema(), other.source);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasSourceBuilder()) {
        this.sourceBuilder = org.example.sharedlibs.Location.newBuilder(other.getSourceBuilder());
      }
      if (isValidValue(fields()[2], other.destination)) {
        this.destination = data().deepCopy(fields()[2].schema(), other.destination);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasDestinationBuilder()) {
        this.destinationBuilder = org.example.sharedlibs.Location.newBuilder(other.getDestinationBuilder());
      }
      if (isValidValue(fields()[3], other.tripStatus)) {
        this.tripStatus = data().deepCopy(fields()[3].schema(), other.tripStatus);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TripDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.sharedlibs.TripDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.tripId)) {
        this.tripId = data().deepCopy(fields()[0].schema(), other.tripId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.source)) {
        this.source = data().deepCopy(fields()[1].schema(), other.source);
        fieldSetFlags()[1] = true;
      }
      this.sourceBuilder = null;
      if (isValidValue(fields()[2], other.destination)) {
        this.destination = data().deepCopy(fields()[2].schema(), other.destination);
        fieldSetFlags()[2] = true;
      }
      this.destinationBuilder = null;
      if (isValidValue(fields()[3], other.tripStatus)) {
        this.tripStatus = data().deepCopy(fields()[3].schema(), other.tripStatus);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'tripId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTripId() {
      return tripId;
    }


    /**
      * Sets the value of the 'tripId' field.
      * @param value The value of 'tripId'.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder setTripId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tripId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tripId' field has been set.
      * @return True if the 'tripId' field has been set, false otherwise.
      */
    public boolean hasTripId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tripId' field.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder clearTripId() {
      tripId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public org.example.sharedlibs.Location getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder setSource(org.example.sharedlibs.Location value) {
      validate(fields()[1], value);
      this.sourceBuilder = null;
      this.source = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'source' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.example.sharedlibs.Location.Builder getSourceBuilder() {
      if (sourceBuilder == null) {
        if (hasSource()) {
          setSourceBuilder(org.example.sharedlibs.Location.newBuilder(source));
        } else {
          setSourceBuilder(org.example.sharedlibs.Location.newBuilder());
        }
      }
      return sourceBuilder;
    }

    /**
     * Sets the Builder instance for the 'source' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.example.sharedlibs.TripDetails.Builder setSourceBuilder(org.example.sharedlibs.Location.Builder value) {
      clearSource();
      sourceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'source' field has an active Builder instance
     * @return True if the 'source' field has an active Builder instance
     */
    public boolean hasSourceBuilder() {
      return sourceBuilder != null;
    }

    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder clearSource() {
      source = null;
      sourceBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'destination' field.
      * @return The value.
      */
    public org.example.sharedlibs.Location getDestination() {
      return destination;
    }


    /**
      * Sets the value of the 'destination' field.
      * @param value The value of 'destination'.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder setDestination(org.example.sharedlibs.Location value) {
      validate(fields()[2], value);
      this.destinationBuilder = null;
      this.destination = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'destination' field has been set.
      * @return True if the 'destination' field has been set, false otherwise.
      */
    public boolean hasDestination() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'destination' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.example.sharedlibs.Location.Builder getDestinationBuilder() {
      if (destinationBuilder == null) {
        if (hasDestination()) {
          setDestinationBuilder(org.example.sharedlibs.Location.newBuilder(destination));
        } else {
          setDestinationBuilder(org.example.sharedlibs.Location.newBuilder());
        }
      }
      return destinationBuilder;
    }

    /**
     * Sets the Builder instance for the 'destination' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.example.sharedlibs.TripDetails.Builder setDestinationBuilder(org.example.sharedlibs.Location.Builder value) {
      clearDestination();
      destinationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'destination' field has an active Builder instance
     * @return True if the 'destination' field has an active Builder instance
     */
    public boolean hasDestinationBuilder() {
      return destinationBuilder != null;
    }

    /**
      * Clears the value of the 'destination' field.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder clearDestination() {
      destination = null;
      destinationBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tripStatus' field.
      * @return The value.
      */
    public org.example.sharedlibs.TRIP_STATUS getTripStatus() {
      return tripStatus;
    }


    /**
      * Sets the value of the 'tripStatus' field.
      * @param value The value of 'tripStatus'.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder setTripStatus(org.example.sharedlibs.TRIP_STATUS value) {
      validate(fields()[3], value);
      this.tripStatus = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tripStatus' field has been set.
      * @return True if the 'tripStatus' field has been set, false otherwise.
      */
    public boolean hasTripStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tripStatus' field.
      * @return This builder.
      */
    public org.example.sharedlibs.TripDetails.Builder clearTripStatus() {
      tripStatus = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TripDetails build() {
      try {
        TripDetails record = new TripDetails();
        record.tripId = fieldSetFlags()[0] ? this.tripId : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (sourceBuilder != null) {
          try {
            record.source = this.sourceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("source"));
            throw e;
          }
        } else {
          record.source = fieldSetFlags()[1] ? this.source : (org.example.sharedlibs.Location) defaultValue(fields()[1]);
        }
        if (destinationBuilder != null) {
          try {
            record.destination = this.destinationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("destination"));
            throw e;
          }
        } else {
          record.destination = fieldSetFlags()[2] ? this.destination : (org.example.sharedlibs.Location) defaultValue(fields()[2]);
        }
        record.tripStatus = fieldSetFlags()[3] ? this.tripStatus : (org.example.sharedlibs.TRIP_STATUS) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TripDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<TripDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TripDetails>
    READER$ = (org.apache.avro.io.DatumReader<TripDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tripId);

    this.source.customEncode(out);

    this.destination.customEncode(out);

    out.writeEnum(this.tripStatus.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);

      if (this.source == null) {
        this.source = new org.example.sharedlibs.Location();
      }
      this.source.customDecode(in);

      if (this.destination == null) {
        this.destination = new org.example.sharedlibs.Location();
      }
      this.destination.customDecode(in);

      this.tripStatus = org.example.sharedlibs.TRIP_STATUS.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tripId = in.readString(this.tripId instanceof Utf8 ? (Utf8)this.tripId : null);
          break;

        case 1:
          if (this.source == null) {
            this.source = new org.example.sharedlibs.Location();
          }
          this.source.customDecode(in);
          break;

        case 2:
          if (this.destination == null) {
            this.destination = new org.example.sharedlibs.Location();
          }
          this.destination.customDecode(in);
          break;

        case 3:
          this.tripStatus = org.example.sharedlibs.TRIP_STATUS.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










