/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.sharedlibs.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Location extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1828301086557435588L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Location\",\"namespace\":\"org.example.sharedlibs.avro\",\"fields\":[{\"name\":\"addressLine1\",\"type\":\"string\"},{\"name\":\"addressLine2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"coordinate\",\"type\":{\"type\":\"record\",\"name\":\"Coordinate\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"provider\",\"type\":\"string\"},{\"name\":\"source\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Location> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Location> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Location> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Location> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Location> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Location to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Location from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Location instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Location fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence addressLine1;
  private java.lang.CharSequence addressLine2;
  private org.example.sharedlibs.avro.Coordinate coordinate;
  private java.lang.CharSequence id;
  private java.lang.CharSequence provider;
  private java.lang.CharSequence source;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Location() {}

  /**
   * All-args constructor.
   * @param addressLine1 The new value for addressLine1
   * @param addressLine2 The new value for addressLine2
   * @param coordinate The new value for coordinate
   * @param id The new value for id
   * @param provider The new value for provider
   * @param source The new value for source
   */
  public Location(java.lang.CharSequence addressLine1, java.lang.CharSequence addressLine2, org.example.sharedlibs.avro.Coordinate coordinate, java.lang.CharSequence id, java.lang.CharSequence provider, java.lang.CharSequence source) {
    this.addressLine1 = addressLine1;
    this.addressLine2 = addressLine2;
    this.coordinate = coordinate;
    this.id = id;
    this.provider = provider;
    this.source = source;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return addressLine1;
    case 1: return addressLine2;
    case 2: return coordinate;
    case 3: return id;
    case 4: return provider;
    case 5: return source;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: addressLine1 = (java.lang.CharSequence)value$; break;
    case 1: addressLine2 = (java.lang.CharSequence)value$; break;
    case 2: coordinate = (org.example.sharedlibs.avro.Coordinate)value$; break;
    case 3: id = (java.lang.CharSequence)value$; break;
    case 4: provider = (java.lang.CharSequence)value$; break;
    case 5: source = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'addressLine1' field.
   * @return The value of the 'addressLine1' field.
   */
  public java.lang.CharSequence getAddressLine1() {
    return addressLine1;
  }


  /**
   * Sets the value of the 'addressLine1' field.
   * @param value the value to set.
   */
  public void setAddressLine1(java.lang.CharSequence value) {
    this.addressLine1 = value;
  }

  /**
   * Gets the value of the 'addressLine2' field.
   * @return The value of the 'addressLine2' field.
   */
  public java.lang.CharSequence getAddressLine2() {
    return addressLine2;
  }


  /**
   * Sets the value of the 'addressLine2' field.
   * @param value the value to set.
   */
  public void setAddressLine2(java.lang.CharSequence value) {
    this.addressLine2 = value;
  }

  /**
   * Gets the value of the 'coordinate' field.
   * @return The value of the 'coordinate' field.
   */
  public org.example.sharedlibs.avro.Coordinate getCoordinate() {
    return coordinate;
  }


  /**
   * Sets the value of the 'coordinate' field.
   * @param value the value to set.
   */
  public void setCoordinate(org.example.sharedlibs.avro.Coordinate value) {
    this.coordinate = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'provider' field.
   * @return The value of the 'provider' field.
   */
  public java.lang.CharSequence getProvider() {
    return provider;
  }


  /**
   * Sets the value of the 'provider' field.
   * @param value the value to set.
   */
  public void setProvider(java.lang.CharSequence value) {
    this.provider = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Creates a new Location RecordBuilder.
   * @return A new Location RecordBuilder
   */
  public static org.example.sharedlibs.avro.Location.Builder newBuilder() {
    return new org.example.sharedlibs.avro.Location.Builder();
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Location RecordBuilder
   */
  public static org.example.sharedlibs.avro.Location.Builder newBuilder(org.example.sharedlibs.avro.Location.Builder other) {
    if (other == null) {
      return new org.example.sharedlibs.avro.Location.Builder();
    } else {
      return new org.example.sharedlibs.avro.Location.Builder(other);
    }
  }

  /**
   * Creates a new Location RecordBuilder by copying an existing Location instance.
   * @param other The existing instance to copy.
   * @return A new Location RecordBuilder
   */
  public static org.example.sharedlibs.avro.Location.Builder newBuilder(org.example.sharedlibs.avro.Location other) {
    if (other == null) {
      return new org.example.sharedlibs.avro.Location.Builder();
    } else {
      return new org.example.sharedlibs.avro.Location.Builder(other);
    }
  }

  /**
   * RecordBuilder for Location instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Location>
    implements org.apache.avro.data.RecordBuilder<Location> {

    private java.lang.CharSequence addressLine1;
    private java.lang.CharSequence addressLine2;
    private org.example.sharedlibs.avro.Coordinate coordinate;
    private org.example.sharedlibs.avro.Coordinate.Builder coordinateBuilder;
    private java.lang.CharSequence id;
    private java.lang.CharSequence provider;
    private java.lang.CharSequence source;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.sharedlibs.avro.Location.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.addressLine1)) {
        this.addressLine1 = data().deepCopy(fields()[0].schema(), other.addressLine1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.addressLine2)) {
        this.addressLine2 = data().deepCopy(fields()[1].schema(), other.addressLine2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.coordinate)) {
        this.coordinate = data().deepCopy(fields()[2].schema(), other.coordinate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasCoordinateBuilder()) {
        this.coordinateBuilder = org.example.sharedlibs.avro.Coordinate.newBuilder(other.getCoordinateBuilder());
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.provider)) {
        this.provider = data().deepCopy(fields()[4].schema(), other.provider);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Location instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.sharedlibs.avro.Location other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.addressLine1)) {
        this.addressLine1 = data().deepCopy(fields()[0].schema(), other.addressLine1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.addressLine2)) {
        this.addressLine2 = data().deepCopy(fields()[1].schema(), other.addressLine2);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.coordinate)) {
        this.coordinate = data().deepCopy(fields()[2].schema(), other.coordinate);
        fieldSetFlags()[2] = true;
      }
      this.coordinateBuilder = null;
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.provider)) {
        this.provider = data().deepCopy(fields()[4].schema(), other.provider);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.source)) {
        this.source = data().deepCopy(fields()[5].schema(), other.source);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'addressLine1' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine1() {
      return addressLine1;
    }


    /**
      * Sets the value of the 'addressLine1' field.
      * @param value The value of 'addressLine1'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setAddressLine1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.addressLine1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'addressLine1' field has been set.
      * @return True if the 'addressLine1' field has been set, false otherwise.
      */
    public boolean hasAddressLine1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'addressLine1' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearAddressLine1() {
      addressLine1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressLine2' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine2() {
      return addressLine2;
    }


    /**
      * Sets the value of the 'addressLine2' field.
      * @param value The value of 'addressLine2'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setAddressLine2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.addressLine2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'addressLine2' field has been set.
      * @return True if the 'addressLine2' field has been set, false otherwise.
      */
    public boolean hasAddressLine2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'addressLine2' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearAddressLine2() {
      addressLine2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'coordinate' field.
      * @return The value.
      */
    public org.example.sharedlibs.avro.Coordinate getCoordinate() {
      return coordinate;
    }


    /**
      * Sets the value of the 'coordinate' field.
      * @param value The value of 'coordinate'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setCoordinate(org.example.sharedlibs.avro.Coordinate value) {
      validate(fields()[2], value);
      this.coordinateBuilder = null;
      this.coordinate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'coordinate' field has been set.
      * @return True if the 'coordinate' field has been set, false otherwise.
      */
    public boolean hasCoordinate() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'coordinate' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.example.sharedlibs.avro.Coordinate.Builder getCoordinateBuilder() {
      if (coordinateBuilder == null) {
        if (hasCoordinate()) {
          setCoordinateBuilder(org.example.sharedlibs.avro.Coordinate.newBuilder(coordinate));
        } else {
          setCoordinateBuilder(org.example.sharedlibs.avro.Coordinate.newBuilder());
        }
      }
      return coordinateBuilder;
    }

    /**
     * Sets the Builder instance for the 'coordinate' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.example.sharedlibs.avro.Location.Builder setCoordinateBuilder(org.example.sharedlibs.avro.Coordinate.Builder value) {
      clearCoordinate();
      coordinateBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'coordinate' field has an active Builder instance
     * @return True if the 'coordinate' field has an active Builder instance
     */
    public boolean hasCoordinateBuilder() {
      return coordinateBuilder != null;
    }

    /**
      * Clears the value of the 'coordinate' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearCoordinate() {
      coordinate = null;
      coordinateBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearId() {
      id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'provider' field.
      * @return The value.
      */
    public java.lang.CharSequence getProvider() {
      return provider;
    }


    /**
      * Sets the value of the 'provider' field.
      * @param value The value of 'provider'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setProvider(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.provider = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'provider' field has been set.
      * @return True if the 'provider' field has been set, false otherwise.
      */
    public boolean hasProvider() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'provider' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearProvider() {
      provider = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.source = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public org.example.sharedlibs.avro.Location.Builder clearSource() {
      source = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Location build() {
      try {
        Location record = new Location();
        record.addressLine1 = fieldSetFlags()[0] ? this.addressLine1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.addressLine2 = fieldSetFlags()[1] ? this.addressLine2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (coordinateBuilder != null) {
          try {
            record.coordinate = this.coordinateBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("coordinate"));
            throw e;
          }
        } else {
          record.coordinate = fieldSetFlags()[2] ? this.coordinate : (org.example.sharedlibs.avro.Coordinate) defaultValue(fields()[2]);
        }
        record.id = fieldSetFlags()[3] ? this.id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.provider = fieldSetFlags()[4] ? this.provider : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.source = fieldSetFlags()[5] ? this.source : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Location>
    WRITER$ = (org.apache.avro.io.DatumWriter<Location>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Location>
    READER$ = (org.apache.avro.io.DatumReader<Location>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.addressLine1);

    if (this.addressLine2 == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.addressLine2);
    }

    this.coordinate.customEncode(out);

    out.writeString(this.id);

    out.writeString(this.provider);

    out.writeString(this.source);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.addressLine1 = in.readString(this.addressLine1 instanceof Utf8 ? (Utf8)this.addressLine1 : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.addressLine2 = null;
      } else {
        this.addressLine2 = in.readString(this.addressLine2 instanceof Utf8 ? (Utf8)this.addressLine2 : null);
      }

      if (this.coordinate == null) {
        this.coordinate = new org.example.sharedlibs.avro.Coordinate();
      }
      this.coordinate.customDecode(in);

      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.provider = in.readString(this.provider instanceof Utf8 ? (Utf8)this.provider : null);

      this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.addressLine1 = in.readString(this.addressLine1 instanceof Utf8 ? (Utf8)this.addressLine1 : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.addressLine2 = null;
          } else {
            this.addressLine2 = in.readString(this.addressLine2 instanceof Utf8 ? (Utf8)this.addressLine2 : null);
          }
          break;

        case 2:
          if (this.coordinate == null) {
            this.coordinate = new org.example.sharedlibs.avro.Coordinate();
          }
          this.coordinate.customDecode(in);
          break;

        case 3:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 4:
          this.provider = in.readString(this.provider instanceof Utf8 ? (Utf8)this.provider : null);
          break;

        case 5:
          this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










