/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.sharedlibs;
@org.apache.avro.specific.AvroGenerated
public enum TRIP_STATUS implements org.apache.avro.generic.GenericEnumSymbol<TRIP_STATUS> {
  STARTED, IN_PROGRESS, COMPLETED, CANCELLED, TRIP_REQUESTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TRIP_STATUS\",\"namespace\":\"org.example.sharedlibs\",\"symbols\":[\"STARTED\",\"IN_PROGRESS\",\"COMPLETED\",\"CANCELLED\",\"TRIP_REQUESTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
