 {
    "type": "record",
    "name": "Location",
   "namespace": "org.example.sharedlibs.trip",
   "fields": [
      {
        "name": "addressLine1",
        "type": "string"
      },
      {
        "name": "addressLine2",
        "type": ["null", "string"],
        "default": null
      },
      {
        "name": "coordinate",
        "type": "org.example.sharedlibs.trips.Coordinate"
      },
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "provider",
        "type": "string"
      },
      {
        "name": "source",
        "type": "string"
      }
    ]
  }
