eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: location-service
server:
  port: 8083



app:
  apis:
    google:
      maps:
        key: 'AIzaSyBYPHOovt6U7KeSsBlfxPsr-H7nG88j1mc'